name: Terraform Plan

on:
  push:
    branches: [autodeploy]

jobs:
  terraform:
    name: "Terraform Init"
    runs-on: ubuntu-latest
   
    env: dev
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      ARM_CLIENT_ID: ${{secrets.TF_ARM_CLIENT_ID}}
      ARM_CLIENT_SECRET: ${{secrets.TF_ARM_CLIENT_SECRET}}
      ARM_SUBSCRIPTION_ID: ${{secrets.TF_ARM_SUBSCRIPTION_ID}}
      ARM_TENANT_ID: ${{secrets.TF_ARM_TENANT_ID}}
      TF_ACTION_WORKING_DIR: '03-autodeploy'


    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v2

      - name: Change directory
        run: |
            pwd
            cd 03-autodeploy
            pwd
            git branch
            echo $ARM_TENANT_ID

      - name: "Setup Terraform"
        uses: hashicorp/setup-terraform@v1
        with:
          ARM_CLIENT_ID: ${{secrets.TF_ARM_CLIENT_ID}}
          ARM_CLIENT_SECRET: ${{secrets.TF_ARM_CLIENT_SECRET}}
          ARM_SUBSCRIPTION_ID: ${{secrets.TF_ARM_SUBSCRIPTION_ID}}
          ARM_TENANT_ID: ${{secrets.TF_ARM_TENANT_ID}}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terrafrom Plan
        run: terraform plan

      

